# Generated by Django 4.0.4 on 2022-05-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_imageurl_rename_color_optioncolor_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeProduct',
        ),
        migrations.AlterModelTable(
            name='likeproduct',
            table='like_products',
        ),
    ]
