# Generated by Django 4.0.4 on 2022-05-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_like_likeproduct_alter_likeproduct_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likeproduct',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='likeproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
