# Generated by Django 4.0.4 on 2022-06-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_product_id_likeproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
