# Generated by Django 4.0.4 on 2022-05-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageUrl',
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='OptionColor',
        ),
        migrations.AlterModelTable(
            name='imageurl',
            table='image_urls',
        ),
        migrations.AlterModelTable(
            name='optioncolor',
            table='option_colors',
        ),
    ]
