# Generated by Django 4.0.4 on 2022-05-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_thumbnail_product_thumbnail_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_1',
            new_name='thumbnail_img_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_2',
        ),
    ]
